create table zones (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(100) not null,
    latitude double precision not null,
    longitude double precision not null
);

create table demand_snapshots (
    id bigint generated by default as identity primary key,
    zone_id bigint not null,
    captured_at timestamp with time zone not null,
    demand double precision not null,
    pickup_minutes integer not null,
    airport_pressure double precision not null,
    ferry_pressure double precision not null,
    event_pressure double precision not null,
    constraint fk_demand_zone foreign key (zone_id) references zones(id)
);

create index idx_demand_zone_time on demand_snapshots(zone_id, captured_at desc);

insert into zones(code, name, latitude, longitude) values
('VIRU', 'Viru / Kesklinn', 59.43696, 24.75353),
('AIRPORT', 'Tallinn Airport', 59.41330, 24.83280),
('ULEMISTE', 'Ülemiste', 59.42130, 24.79380),
('TELLISKIVI', 'Telliskivi', 59.43940, 24.72960),
('NOBLESSNER', 'Noblessner', 59.45120, 24.72840),
('BALTI_JAAM', 'Balti jaam', 59.44080, 24.73740),
('TERMINAL_D', 'Terminal D', 59.44390, 24.76760),
('TERMINAL_A', 'Terminal A', 59.44410, 24.76030),
('MUSTAMAE', 'Mustamäe Keskus', 59.40470, 24.68540),
('KRISTIINE', 'Kristiine Keskus', 59.42650, 24.72260),
('LASNAMAE', 'Lasnamäe Centrum', 59.43870, 24.88040),
('PIRITA', 'Pirita', 59.46870, 24.83000),
('ROCCA', 'Rocca al Mare', 59.42680, 24.65020),
('KAKUMAE', 'Kakumäe', 59.45190, 24.57590),
('SIKUPILLI', 'Sikupilli', 59.42710, 24.79280);
